# -*- coding: utf-8 -*-
"""Torch_MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hoBlvrAJ2DwC0QPLbwug5qcaOkAcGJCo
"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=transforms.ToTensor()
)

test_data = datasets.MNIST(
    root="data",
    train=False,
    download=True,
    transform=transforms.ToTensor()
)

batch_size = 64

train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
      nn.Linear(28*28, 512),
      nn.ReLU(),
      nn.Linear(512, 512),
      nn.ReLU(),
      nn.Linear(512, 10)
    )

  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits

model = Net().to(device)
print(model)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

def train(DataLoader, model, loss_fn, optimizer):
  size = len(DataLoader.dataset)
  model.train()
  for batch, (X, y) in enumerate(DataLoader):
    X, y = X.to(device), y.to(device)

    pred = model(X)
    loss = loss_fn(pred, y)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    if batch % 100 == 0:
      loss, current = loss.item(), batch * len(X)
      print(f"loss: {loss:>7f} [{current:>5d}/{size:>5d}]")

def test(DataLoader, model, loss_fn):
  size = len(DataLoader.dataset)
  num_batches = len(DataLoader)
  model.eval()
  test_loss, correct = 0, 0
  with torch.inference_mode():
    for X, y in DataLoader:
      X, y = X.to(device), y.to(device)
      pred = model(X)
      test_loss += loss_fn(pred, y).item()
      correct += (pred.argmax(1) == y).type(torch.float).sum().item()
  test_loss /= num_batches
  correct /= size
  print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

epochs = 5
for t in range(epochs):
  print(f"Epoch {t+1}\n-------------------------------")
  train(train_dataloader, model, loss_fn, optimizer)
  test(test_dataloader, model, loss_fn)
  print("Done!")

torch.save(model.state_dict(), "mnist_base_model.pth")
print("Saved PyTorch Model State to mnist_base_model.pth")

model = Net().to(device)
model.load_state_dict(torch.load("mnist_base_model.pth"))
model.eval()

from PIL import Image

image_path = "mynumber.jpg"
image = Image.open(image_path).convert("L")
transform = transforms.Compose([
  transforms.Resize((28, 28)),
  transforms.ToTensor()
])
image = transform(image).to(device)

with torch.inference_mode():
  output = model(image)
  prediction = torch.argmax(output).item()

print(f"Predicted digit: {prediction}")